config/routes.rb
Rails.application.routes.draw do
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?

  root "pages#index"

  resources :pages do
    resource :check, only: [:create]
  end

  get "up" => "rails/health#show", as: :rails_health_check
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/page.rb
class Page < ApplicationRecord
  CHECK_TYPES = %w[text exists not_exists]

  belongs_to :last_result, class_name: "Result", optional: true
  has_many :results, dependent: :destroy

  validates :name, presence: true
  validates :url, presence: true
  validates :check_type, presence: true, inclusion: { in: CHECK_TYPES }
  validates :selector, presence: true
  validates :match_text, presence: true, if: :text?

  def text?
    check_type == "text"
  end

  def run_and_notify
    run_check
    last_result.notify
  end

  def run_check
    scraper = Scraper.new(url: url)

    result = case check_type
              when "text"
                scraper.text(selector: selector).downcase == match_text.downcase
              when "exists"
                scraper.present?(selector: selector)
              when "not_exists"
                !scraper.present?(selector: selector)
              end

    result = results.create(success: result)
    update(last_result: result)
  end
end

app/models/result.rb
class Result < ApplicationRecord
  belongs_to :page

  def notify
    return unless success?
    UserMailer.success(page: page, result: self).deliver_later
  end
end

app/models/scraper.rb
require "net/http"

class Scraper
  attr_reader :document

  def initialize(url:)
    response = Net::HTTP.get(URI.parse(url))
    @document = Nokogiri::HTML(response)
  end

  def text(selector:)
    document.at_css(selector).text
  end

  def present?(selector:)
    document.at_css(selector).present?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/checks_controller.rb
class ChecksController < ApplicationController
  before_action :set_page

  def create
    @page.run_check
    redirect_to @page
  end

  private
    def set_page
      @page = Page.find(params[:page_id])
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :set_page, only: %i[show edit update destroy ]

  # GET /pages or /pages.json
  def index
    @pages = Page.includes(:last_result)
  end

  # GET /pages/1 or /pages/1.json
  def show
  end

  # GET /pages/new
  def new
    @page = Page.new
  end

  # GET /pages/1/edit
  def edit
  end

  # POST /pages or /pages.json
  def create
    @page = Page.new(page_params)

    respond_to do |format|
      if @page.save
        format.html { redirect_to @page, notice: "Page was successfully created." }
        format.json { render :show, status: :created, location: @page }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @page.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pages/1 or /pages/1.json
  def update
    respond_to do |format|
      if @page.update(page_params)
        format.html { redirect_to @page, notice: "Page was successfully updated." }
        format.json { render :show, status: :ok, location: @page }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @page.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pages/1 or /pages/1.json
  def destroy
    @page.destroy!

    respond_to do |format|
      format.html { redirect_to pages_path, status: :see_other, notice: "Page was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_page
      @page = Page.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def page_params
      params.require(:page).permit(:name, :url, :check_type, :selector, :match_text)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Webscraper</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <main class="container mx-auto mt-28 px-5 flex">
      <%= yield %>
    </main>
  </body>
</html>

app/views/pages/_form.html.erb
<%= form_with(model: page, class: "contents") do |form| %>
  <% if page.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-md mt-3">
      <h2><%= pluralize(page.errors.count, "error") %> prohibited this page from being saved:</h2>

      <ul class="list-disc ml-6">
        <% page.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :name %>
    <%= form.text_field :name, class: ["block shadow rounded-md border outline-none px-3 py-2 mt-2 w-full", {"border-gray-400 focus:outline-blue-600": page.errors[:name].none?, "border-red-400 focus:outline-red-600": page.errors[:name].any?}] %>
  </div>

  <div class="my-5">
    <%= form.label :url %>
    <%= form.url_field :url, class: ["block shadow rounded-md border outline-none px-3 py-2 mt-2 w-full", {"border-gray-400 focus:outline-blue-600": page.errors[:url].none?, "border-red-400 focus:outline-red-600": page.errors[:url].any?}] %>
  </div>

  <div class="my-5">
    <%= form.label :check_type %>
    <%= form.select :check_type,
      options_for_select(Page::CHECK_TYPES.map { |type| [type.humanize, type] }, page.check_type),
      {},
      class: ["block shadow rounded-md border outline-none px-3 py-2 mt-2 w-full",
        {"border-gray-400 focus:outline-blue-600": page.errors[:check_type].none?,
         "border-red-400 focus:outline-red-600": page.errors[:check_type].any?}] %>
  </div>

  <div class="my-5">
    <%= form.label :selector %>
    <%= form.text_field :selector, class: ["block shadow rounded-md border outline-none px-3 py-2 mt-2 w-full", {"border-gray-400 focus:outline-blue-600": page.errors[:selector].none?, "border-red-400 focus:outline-red-600": page.errors[:selector].any?}] %>
  </div>

  <div class="my-5">
    <%= form.label :match_text %>
    <%= form.text_field :match_text, class: ["block shadow rounded-md border outline-none px-3 py-2 mt-2 w-full", {"border-gray-400 focus:outline-blue-600": page.errors[:match_text].none?, "border-red-400 focus:outline-red-600": page.errors[:match_text].any?}] %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-md px-3.5 py-2.5 bg-blue-600 hover:bg-blue-500 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/pages/_page.html.erb
<%= link_to page, id: dom_id(page), class: "block w-fit bg-gray-50 p-4 rounded-md shadow hover:bg-gray-100" do %>
  <p class="font-bold">
    <%= page.name %>
  </p>

  <div class="font-medium">
    <p class="text-sm text-blue-500"><%= page.url.sub(/^https?:\/\//, "") %></p>
    <%= render partial: "results/result", locals: { result: page.last_result } %>
  </div>
<% end %>

app/views/pages/edit.html.erb
<div class="md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Edit page</h1>

  <%= render "form", page: @page %>

  <%= link_to "Cancel", @page, class: "ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
</div>

app/views/pages/index.html.erb
<% content_for :title, "Pages" %>

<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-md inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Pages</h1>
    <%= link_to "Monitor new page", new_page_path, class: "rounded-md px-3.5 py-2.5 bg-blue-600 hover:bg-blue-500 text-white block font-medium" %>
  </div>

  <div id="pages" class="flex flex-wrap gap-4 mt-5 min-w-full">
    <% if @pages.any? %>
      <%= render partial: "page", collection: @pages.order(created_at: :desc) %>
    <% else %>
      <p class="text-center my-10">No pages found.</p>
    <% end %>
  </div>
</div>

app/views/pages/new.html.erb
<% content_for :title, "New page" %>

<div class="md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New page</h1>

  <%= render "form", page: @page %>

  <%= link_to "Back to pages", pages_path, class: "ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
</div>

app/views/pages/show.html.erb
<div class="md:w-2/3 w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-md inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="mb-5">
    <h1 class="flex items-center gap-3 mb-3 font-bold text-2xl truncate">
      <%= link_to pages_path, class: "hover:bg-gray-100 rounded-md p-1" do %>
        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" class="size-6">
          <path fill-rule="evenodd" d="M11.78 5.22a.75.75 0 0 1 0 1.06L8.06 10l3.72 3.72a.75.75 0 1 1-1.06 1.06l-4.25-4.25a.75.75 0 0 1 0-1.06l4.25-4.25a.75.75 0 0 1 1.06 0Z" clip-rule="evenodd" />
        </svg>
      <% end %>
      <%= @page.name %>
    </h1>

    <%= link_to @page.url, @page.url, target: "_blank", class: "text-blue-500 font-medium hover:text-blue-600 hover:underline" %>

    <p>Check type: <span><%= @page.check_type %></span></p>

    <p>Selector: <span><%= @page.selector %></span></p>

    <% if @page.text? %>
      <p>Match text: <span><%= @page.match_text %></span></p>
    <% end %>
  </div>

  <%= link_to "Edit", edit_page_path(@page), class: "mt-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>

  <div class="inline-flex ml-2">
    <%= button_to "Destroy", @page, method: :delete, class: "mt-2 rounded-md px-3.5 py-2.5 text-white bg-red-600 hover:bg-red-500 font-medium" %>
  </div>

  <div class="inline-flex ml-2 mb-5">
    <%= button_to "Run", page_check_path(@page), method: :post, class: "mt-2 rounded-md px-3.5 py-2.5 text-white bg-blue-600 hover:bg-blue-500 font-medium" %>
  </div>

  <h4 class="font-bold text-lg mt-5 mb-3">Results</h4>

  <%= render partial: "results/result", collection: @page.results.order(created_at: :desc).limit(10) %>
</div>

app/views/results/_result.html.erb
<%= turbo_frame_tag result do %>
  <% if result.present? %>
    <div class="flex items-center gap-2">
      <span class="flex items-center gap-1 text-sm font-bold <%= result.success ? "text-green-500" : "text-red-500" %>">
        <% if result.success %>
          <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" class="size-5">
            <path fill-rule="evenodd" d="M10 18a8 8 0 1 0 0-16 8 8 0 0 0 0 16Zm3.857-9.809a.75.75 0 0 0-1.214-.882l-3.483 4.79-1.88-1.88a.75.75 0 1 0-1.06 1.061l2.5 2.5a.75.75 0 0 0 1.137-.089l4-5.5Z" clip-rule="evenodd" />
          </svg>
          Found on page
        <% else %>
          <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" class="size-5">
            <path fill-rule="evenodd" d="M10 18a8 8 0 1 0 0-16 8 8 0 0 0 0 16ZM8.28 7.22a.75.75 0 0 0-1.06 1.06L8.94 10l-1.72 1.72a.75.75 0 1 0 1.06 1.06L10 11.06l1.72 1.72a.75.75 0 1 0 1.06-1.06L11.06 10l1.72-1.72a.75.75 0 0 0-1.06-1.06L10 8.94 8.28 7.22Z" clip-rule="evenodd" />
          </svg>
          Not found on page
        <% end %>
      </span>

      <span class="text-gray-500 text-sm font-medium">
        <%= time_ago_in_words(result.created_at) %> ago
      </span>
    </div>
  <% else %>
    <p class="text-gray-500 text-sm font-medium">No result to display</p>
  <% end %>
<% end %>